server:
  port: 8091
spring:
  application:
    name: config-server-demo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DelOmarPalomino/bootcamp-config-server.git
          default-label: main
  profiles:
    active: git